Update index.html
amri-tah/burntbrotta pull request #16
Opened 2024-12-25 06:57 UTC by Shreya12125

Updated the index.html by adding the Default profile picture for all users, Username, date, and time of posting Star ratings and review text

2024-12-25 07:55 UTC, amri-tah commented on index.html
> +</style>
Please move this to its corresponding CSS file

2024-12-25 07:57 UTC, amri-tah requested changes
@Shreya12125 Please make these changes, and attach images of the changes once its done in this PR thread!

2024-12-25 07:57 UTC, amri-tah commented on index.html
> +  }
This needs to be in the individual recipe page, and not the landing page. The JavaScript code should be in its JS file as well.

2024-12-27 15:39 UTC, amri-tah commented
@Shreya12125 Please attach the images of the changes you made in the website in this PR thread

2024-12-28 12:05 UTC, Shreya12125 commented
Image of the output
![image](https://github.com/user-attachments/assets/82ae11cb-3084-4a2c-8fda-bd409e0daae3)

2024-12-31 11:44 UTC, amri-tah commented on index.html
> +</style>
This is still not fixed, please remove it from the index.html file to CSS files/recipepage.css

2024-12-31 11:45 UTC, amri-tah commented on index.html
> +  }
This too, 
![image](https://github.com/user-attachments/assets/1d0ba60d-51e4-4aa8-ab5f-337752316daa)

This is not supposed to get displayed in the landing page

2024-12-31 11:46 UTC, amri-tah commented on index.html
> +  ];
This data needs to be read from the recipes.json file for each individual recipe

2024-12-31 11:48 UTC, amri-tah commented
> Image of the output ![image](https://private-user-images.githubusercontent.com/164351677/399078123-2d0259a6-8c11-4a73-b48e-8145f2635d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NDU5MTMsIm5iZiI6MTczNTY0NTYxMywicGF0aCI6Ii8xNjQzNTE2NzcvMzk5MDc4MTIzLTJkMDI1OWE2LThjMTEtNGE3My1iNDhlLTgxNDVmMjYzNWQxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxMTQ2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTExY2I3OTFjYjg2NGVmYTIwZTY2MjdlMDVhYzk5Yjg3NzMxMGJiODczM2YzMDZhMzM4ZTlhNjA5NjgyZDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AmlsdwS7sSSmXOyZBc2596SxnLAyoIn58T3GOgliOlc)


Could also try to improve the UI a bit

2025-01-04 05:29 UTC, amri-tah commented
Hey @Shreya12125, thanks for your effort on this! I feel this issue needs a bit more exploration, so I’ll have to reassign it to someone else to ensure we get the best solution. Hope that’s okay!

2025-01-04 05:29 UTC, closed without merging